# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faae9028c7cef186a17cbffdcd06fb617b56ea28bd68f69bcc1264f898ec560f373519d38a72e049f7da332da46885a246596db65101a528d404bbcfa1a213c9

test:
  secret_key_base: ce69507425307f26bf90d2736d83aecd7977a57d8bd36dd6b7062bcb7498a4e6a90e01e875ac86587efae8121101f7e6585fd232efef63f4b4522318f8fe3e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
